harness/lite-engine

internal/docker/jsonmessage/jsonmessage.go

If image was not pulled due to storage issue, earlier it was just giving image not found error which is misleading. Actual err:
`failed to register layer: re-exec error: exit status 1: output: BackupWrite \\\\?\\C:\\ProgramData\\docker\\windowsfilter\\621b3a2539d0808319774d93840dd04d453b5a4fbca1c8580fd5c6822d972395\\UtilityVM\\Files\\Windows\\Fonts\\msyh.ttc: There is not enough space on the disk`

Adding step logs for image pull errors

---

.gitignore
setup/setup.go

This is required for osx support. "docker" command won't work. You need to pass full path.

append usr/local/bin path for osx docker

---

api/api.go
handler/health.go

DockerInstalled, GitInstalled & LiteEngineLogs variables are not used in runner. So, it will be backward compatible.

Remove drone & git checks from health check api

---

engine/docker/docker.go

Some CI pipelines failed with errors:
1. Error response from daemon: Get "https://registry-1.docker.io/v2/mikesir87/aws-cli/manifests/sha256:064523bff733063ccabe2110314c534a4c6a0ad79ee3488e536a6c5de37c6835": EOF
2. Error response from daemon: Head "https://registry-1.docker.io/v2/harness/drone-git/manifests/1.2.3": Get "https://auth.docker.io/token?scope=repository%3Aharness%2Fdrone-git%3Apull&service=registry.docker.io": EOF
Added retries to reduce these issues.

Add retries for image pull op

---

cli/server/server.go

Overload .env variables if env file present. This is for ensuring that PATH variable value of host machine is set and not cloud init script one

overload .env variables if env file present

---

ti/callgraph/upload.go
ti/client/http.go
ti/instrumentation/utils.go
ti/report/report.go

Cloud Lite Engine does not send commit_link data to TI service to write into tsdb. This commit fixes this.

(fix): Cloud Lite Engine does not send commit_link data

---

pipeline/runtime/common.go

If the last statement is a comment then we append the output var command to a comment which also comments it out and it does create an output file. This change puts the output var cmd on a new line to ensure it always executes

[fix]: [CI-7224]: Fix output variable not found error

---

cli/client/client.go
cli/client/http.go
cli/client/noop.go

We want to be able to support easy scale testing in AWS runner without having to interact with the lite engine. This PR adds a noop client to mock out the lite engine ops

(feat): add noop client for lite engine operations

---

livelog/livelog.go

Context here: https://harness.atlassian.net/browse/CI-7973
This should fix the issue VS is seeing for truncated logs

update lock so that flush() does not return if there is any Write in progress

---

engine/engine.go

Currently even though we create the dir with 0777, the default umask of 022 creates the dir with 0755. Hence we need to explicitly chmod to achieve this. Please refer to https://harness.atlassian.net/browse/CI-8107 for more details as to why its needed.

[feat]: [CI-8188]: 0777 permission must be given to /tmp/engine

---

api/api.go
handler/destroy.go
livelog/livelog.go
livelog/livelog_test.go
pipeline/runtime/step_executor.go

i) Adds lite engine log upload as part of the destroy call. We have seen many cases where debugging is difficult because of no lite engine logs. This will upload lite-engine.log  to help with debugging. 
ii) Fixes an issue where 5MB log limit was not being honored for VMs.

add support for lite engine log upload and fix log limit issue

---

engine/docker/docker.go
engine/engine.go
pipeline/runtime/step_executor.go

Currently we are running the go routine for detach step before pulling the image for docker step. We have seen problems in some pipelines where due to image not being pulled the execution fails for different reasons. Here is one such example - https://harness.atlassian.net/browse/CI-9246. 
Have moved the go routine after pulling and creating the docker container.

[CI-9246]: Do background execution for detach step only after pulling image

---

api/api.go
go.mod
go.sum
handler/destroy.go
handler/step.go
pipeline/env_state.go
pipeline/runtime/step_executor.go

This change add support to do step status directly from LE to manager.
Added change to store prev step envs which are required for github action plugins. This same logic is used in dlite runner.

Add support to update step status from LE directly

---

pipeline/runtime/runtest.go
pipeline/runtime/runtest_test.go
ti/instrumentation/python/pytest.go
ti/instrumentation/python/unittest.go
ti/instrumentation/ruby/rspec.go
ti/report/report.go

- added output command to rspec and python runners if user does not provided the command
- added default path to python and ruby if not exist

Use default values for python and ruby test generation

---

pipeline/runtime/run.go
pipeline/runtime/runtest.go
pipeline/runtime/runtest_test.go
ti/report/parser/junit/gojunit/ingest.go
ti/report/parser/junit/gojunit/ingest_test.go
ti/report/parser/junit/gojunit/ingesters.go
ti/report/parser/junit/gojunit/testdata/cypress-custom.xml
ti/report/parser/junit/gojunit/testdata/cypress.xml
ti/report/parser/junit/junit.go
ti/report/parser/junit/junit_test.go
ti/report/report.go

Please check the xml file in the test example to see the kind of xml we are trying to get the filename for. 
If there is a test suite called Root Suite then the filename used in that must be propagated to other test suites. If any test suite and test case does not have a filename then the one from the Root Suite must be used.

[feat]: [CI-9899]: Parse filename in cypress juint xml

---

ti/instrumentation/instrumentation.go

Before if it was a manual execution, RunOnlySelected tests was made false in the test selection part but now that was skipped. And hence in case of manual execution we were running selected tests which were empty since we did not select any tests to run. Found this issue when trying to setup harness code with TI since that is the only flow we are seeing TI defined manual executions still.

[feat]: [CI-9776]: Fix case for ignoreInstr

---

ti/instrumentation/java/gradle.go

Currently we are checking for gradlew in / instead of /harness. This change will check for gradlew in the correct place

[feat]: [CI-11342]: Fix picking gradlew

---

pipeline/runtime/runtestsV2.go
pipeline/runtime/runtestsV2_test.go
ti/instrumentation/utils.go
ti/instrumentation/utils_test.go

Description-
Added Functionality to Get agent v2 links from TI service and download agents for Runtest V2
Also changed outpath to callgraph/cg dir ,
Tested for all languages both functional and UTs.
Call graph and test nodes are generated and can be seen in the step Logs

[feat]: [CI-11538]: Update agent download links for v2

---

pipeline/runtime/common.go
pipeline/runtime/runtestsV2.go
pipeline/runtime/runtestsV2_test.go
ti/config/config.go
ti/instrumentation/instrumentation.go
ti/instrumentation/java/helper.go
ti/instrumentation/ruby/helper.go
ti/instrumentation/ruby/rspec.go

Added auto-test-detection for java, ruby and python for test splitting and parallelism.
In case of prallelism if its first run or if all cases are selected then tests will be auto detected and populated in filter file.

[CI-11492]: Add autodetection splitting

---

pipeline/runtime/runtestsV2.go
pipeline/runtime/runtestsV2_test.go
ti/instrumentation/instrumentation.go
ti/instrumentation/utils.go

Currently test globs passed from the user in the runtest and test steps are not being sent to ti-service. TI service needs them to check if a changed file is a test file or no
Testing for vagrant ruby repo which does not use default globs
Before changes, if a test file is modified, it is not selected to run
With changes, modfying a test file we can see tests are selected (prints look different for debugging)

[feat]: [CI-12471]: Send testglobs from lite-engine to ti-service

---

go.mod
go.sum
pipeline/runtime/run.go
pipeline/runtime/runtest.go
pipeline/runtime/runtestsV2.go
ti/savings/dlc/dlc.go
ti/savings/savings.go

We will parse the cache metrics file created by the buildx plugin if it exists and upload savings data to ti-service

[feat]: [CI-12621]: Upload savings for DLC

---

go.mod
go.sum
ti/savings/dlc/dlc.go

Successful metrics parsing in lite-engine and upload to ti-service
Example with ERROR layer

[feat]: [CI-12621]: Move cache metrics struct to ti-client

---

pipeline/runtime/runtestsV2.go

Full Run
Optimized Run
Savings Table

[feat]: [CI-12982]: Add ParseSavings Support for RunTestV2

---

handler/setup.go
livelog/livelog.go
logstream/remote/http.go
osstats/collector.go

Added following changes.
1. Added process dump in collector if `HARNESS_ENABLE_DEBUG_LOGS` env is set
2. Added timeouts for log upload requests so that backoff can work.

feat: [CI-12843]: Enable process information in LE logs

---

pipeline/runtime/common.go
pipeline/runtime/run.go
pipeline/runtime/runtest.go
pipeline/runtime/runtestsV2.go
ti/savings/savings.go

If the cache intel restore step is successful then it is OPTIMZED. If it exists but not successful it is a FULL_RUN
Tested on devspace, we can see optimization state, time saved populated and showing on UI

[feat]: [CI-13358]: Show stage savings for cache intel

---

pipeline/runtime/step_executor.go
ti/savings/savings.go

Currently optimization state is not returned for a failed step. This should be done to make sure cache intel FULL_RUN is saved since cache intel is a FULL_RUN if the restore-cache-harness step fails
Tested on local
FULL_RUN (where restore step fails)
We can see that we are returning the optimization state
Optimized Run

[feat]: [CI-13579]: Return  Optimization state for Failed Step

---

pipeline/runtime/runtestsV2.go
ti/instrumentation/csharp/helper.go
ti/instrumentation/utils.go
ti/report/parser/junit/gojunit/ingesters.go
ti/report/parser/junit/gojunit/parse.go

Adding support for .Net to TI
This includes:
* Downloading the agent's archive
* Unzipping the archive
* Configuring the environment variables and writing a configuration file
* Parsing the results - for .Net it can support JUnit and TRX formats, so here we add support for TRX by converting them back to JUnit format in memory and letting the process continue as is
One thing to note - as opposed to other agents, .net is added later to the v2 step, so we don't prevent the use of the v2 step in case the .net agent is failed to download - we would just initiate a warning and won't apply the .net changes.
This change requires the changes from this PR: https://github.com/wings-software/harness-ti/pull/170 but it wouldn't fail if they are missing.
* Tested with and without the physical agent …

feat: [CI-13332]:  Add support for dotnet agent

---

engine/engine.go

Currently lite engine skips processing a file if it already exists. We should ideally overwrite the file with the content provided. Runner creates a exec task with some files. 
Updated createFiles func to check if file exists -> update permissions to write it -> log error in chmod -> continue with os.create (it will truncate existing files)

support for overwriting existing files

---

ti/savings/cache/gradle/parser.go

In this PR once we read a profile report we append it with .processed so that it isnt read again. This ensures that the original file is not processed by multiple steps
Tested on devspace
Without changes we can see that non build cache step after the build cache also is optimized
After changes we can see that the step after the build cache step does not upload any optimization state and we can see that the profile file is not present anymore

[feat]: [CI-12024]: Gradle Build Cache Savings should only be Parsed Once

---

engine/docker/docker.go

Changes : removed http dependency as security concern from secops team
Tested both  http  & https traffic with https proxy in qa for this 
linux :
**http**: 
https://qa.harness.io/ng/account/h61p38AZSV6MzEkpWWBtew/all/orgs/default/projects/SatyaTest/pipelines/secureConnectAuth_DockerBuildAndPush_Clone/deployments/6a_hG9xJTL-JYn3VI_rbGQ/pipeline?storeType=INLINE
**https**:
https://qa.harness.io/ng/account/h61p38AZSV6MzEkpWWBtew/all/orgs/default/projects/SatyaTest/pipelines/secureConnectAuth_DockerBuildAndPush_Clone/executions/Dez39Ar6R--lUWoRv3iXBA/pipeline?storeType=INLINE&step=Ewkx2dbeRlO9mpTS4G0Dmw&stage=uoYKbi3QREe7RbiobBQo0A&childStage=&stageExecId=
windows : 
**http**:
https://qa.harness.io/ng/account/h61p38AZSV6MzEkpWWBtew/all/orgs/default/projects/SatyaTest/pipelines/secureConnectAu …

[feat]: [CI-14538]: remove http dependency
